name       : grilo-plugins
version    : 0.3.9
release    : 22
source     :
    - https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.9.tar.xz : 41223e236a0b3e864b6d282f1a93a061f49ee18c86fc88fe462c4a6cca2268c3
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Plugins for Grilo
description: |
    Plugins for Grilo
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(libarchive)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - itstool
setup      : |
    %meson_configure \
        -Denable-dleyna=yes \
        -Denable-flickr=yes \
        -Denable-gravatar=yes \
        -Denable-jamendo=yes \
        -Denable-lua-factory=no \
        -Denable-magnatune=yes \
        -Denable-shoutcast=yes \
        -Denable-youtube=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
