name        : grilo-plugins
version     : 0.2.16
release     : 6
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/grilo-plugins/0.2/grilo-plugins-0.2.16.tar.xz : 80b4571f9db6df0d5f0873d30f2ee475204f5831d2974b89c58423d6ffac5203
license     :
    - GPLv2+
summary     : Plugins for Grilo
builddeps   :
    - pkgconfig(goa-1.0)
    - pkgconfig(grilo-net-0.2)
    - pkgconfig(libgdata)
    - pkgconfig(gmime-2.6)
    - pkgconfig(oauth)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(totem-plparser)
    - pkgconfig(sqlite3)
    - pkgconfig(libmediaart-2.0)
    - itstool
description : |
    Plugins for Grilo
setup      : |
    %configure --disable-static \
               --enable-goa \
               --enable-filesystem \
               --enable-jamendo \
               --enable-flickr \
               --enable-shoutcast \
               --enable-apple-trailers \
               --enable-magnatune \
               --enable-youtube \
               --enable-gravatar
build      : |
    %make
install    : |
    %make_install
