name       : grilo-plugins
version    : 0.3.8
release    : 21
source     :
    - https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.8.tar.xz : 4cdd770b1554ee49cf77705401a35daa3ebff81badc05bd69d7240f50e60d65b
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Plugins for Grilo
description: |
    Plugins for Grilo
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(libarchive)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - itstool
setup      : |
    %meson_configure \
        -Denable-dleyna=yes \
        -Denable-flickr=yes \
        -Denable-gravatar=yes \
        -Denable-jamendo=yes \
        -Denable-magnatune=yes \
        -Denable-shoutcast=yes \
        -Denable-youtube=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
