name       : grilo-plugins
version    : 0.3.6
release    : 19
source     :
    - https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.6.tar.xz : d9e07ec0aeb1e52270b6a3629c9f040d6f40808834aa3c8e2da90fecb7c31275
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Plugins for Grilo
description: |
    Plugins for Grilo
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(libarchive)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-apple-trailers \
               --enable-filesystem \
               --enable-flickr \
               --enable-goa \
               --enable-gravatar \
               --enable-jamendo \
               --enable-magnatune \
               --enable-shoutcast \
               --enable-youtube
build      : |
    %make
install    : |
    %make_install
