name       : grilo-plugins
version    : 0.3.4
release    : 14
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/grilo-plugins/0.3/grilo-plugins-0.3.4.tar.xz : 990282a518968c52f6a67b96c6b708e236a59da1c7c920ed45e6316ab49ddeb5
license    :
    - GPLv2+
component  : desktop.gnome.core
summary    : Plugins for Grilo
description: |
    Plugins for Grilo
builddeps  :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-2.6)
    - pkgconfig(goa-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(libarchive)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-miner-1.0)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-apple-trailers \
               --enable-filesystem \
               --enable-flickr \
               --enable-goa \
               --enable-gravatar \
               --enable-jamendo \
               --enable-magnatune \
               --enable-shoutcast \
               --enable-youtube
build      : |
    %make
install    : |
    %make_install
