name        : grilo-plugins
version     : 0.2.17
release     : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/grilo-plugins/0.2/grilo-plugins-0.2.17.tar.xz : 337669098cddf64a84fa9398aa1d7f994fea84bc5f7f1b348e1288f135713781
license     :
    - GPLv2+
summary     : Plugins for Grilo
description : |
    Plugins for Grilo
builddeps   :
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-2.6)
    - pkgconfig(goa-1.0)
    - pkgconfig(grilo-net-0.2)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-apple-trailers \
               --enable-filesystem \
               --enable-flickr \
               --enable-goa \
               --enable-gravatar \
               --enable-jamendo \
               --enable-magnatune \
               --enable-shoutcast \
               --enable-youtube
build      : |
    %make
install    : |
    %make_install
