name       : grilo-plugins
version    : 0.3.11
release    : 26
source     :
    - https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.11.tar.xz : dde2e605b1994341c6bf012493e056b406b08571834dea3b3c671d5b8b1dcd73
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Plugins for Grilo
description: |
    Plugins for Grilo
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(dleyna-server-service-1.0)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(grilo-net-0.3)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libgdata)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(lua)
    - pkgconfig(oauth)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(totem-plparser)
    - pkgconfig(tracker-sparql-2.0)
    - gperf
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/tracker-utils-use-define-for-queries.patch
    %meson_configure \
        -Denable-dleyna=yes \
        -Denable-flickr=yes \
        -Denable-gravatar=yes \
        -Denable-jamendo=yes \
        -Denable-lua-factory=yes \
        -Denable-magnatune=yes \
        -Denable-shoutcast=yes \
        -Denable-youtube=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
